spring:
  datasource:
    url: jdbc:mysql://43.200.20.107:3306/jwt
    username: chjeong
    password: c06230731
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-aql: true

jwt:
  secret: c25zc2VjcmV0a2V5c25zc2VjcmV0a2V5c25zc2VjcmV0a2V5